# -*- coding: utf-8 -*-
"""Work1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17HbEOe0WE99JiwGMAXcigJHaJwvZq_o_
"""

a = int (input("Введите делимое: "))
b = int (input("Введите делитель: "))
try:
  x=a//b
  print(x)
except ZeroDivisionError :
  print("На 0 делить нельзя!!!")
finally: 
  print("Сработал блок файнали")

import random
a=random.randint(1,6)
b=random.randint(1,6)
c=random.randint(1,6)
d=random.randint(1,6)
total=a+b+c+d
print("Бросок 1:",a, "Бросок 2:", b, "Бросок 3:", c, "Бросок 4:",d)
print("Общая сумма:", total)

import random
k=4
y=[]
while k !=0:
  x=random.randint(1,6)
  k-=1
  y.append(x)
  print(y)
print("Суммарное значение 4 бросков:", sum(y))

import random
chars = "+-/*!&$#?=@<>abcdefghijklnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
length=input('Длина пароля: '+ "\n")
password=""
try:  
  length=int(length)
  for i in range(length):
    password += random.choice(chars)
  print("Ваш пароль: ", password)
except ValueError:
  print ("Ты ввел не цифры, а быуквы или символы. Исправься!")
finally:
  password=""
  length=input('Длина пароля: '+"\n")
  length=int(length)
  for i in range(length):
    password += random.choice(chars)
  print("Ваш пароль: ", password)

import random 
arr=[1,2,3,4,5, 'test1','tast2','test3']
#print("Случайное число: ", random.choice(arr))
print(len(arr))

import random
y=random.uniform(1.5,2.5)
print(y)